# Generated by Django 3.2.8 on 2021-10-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_vault_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vault',
            name='content',
        ),
        migrations.AddField(
            model_name='vault',
            name='email',
            field=models.EmailField(default='mail@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='vault',
            name='other_info',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='vault',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vault',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
