# Generated by Django 3.2.8 on 2021-11-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='pwd_key',
            field=models.CharField(default='myPassword', max_length=255),
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('enc_pwd', models.CharField(max_length=255)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.vault')),
            ],
        ),
    ]
