# Generated by Django 3.2.8 on 2021-11-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_auto_20211102_2019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.RenameField(
            model_name='keys',
            old_name='enc_pwd',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='vault',
            old_name='pwd_key',
            new_name='enc_pwd',
        ),
    ]
