# Generated by Django 3.2.8 on 2021-11-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_auto_20211103_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keys',
            old_name='pwd',
            new_name='enc_pwd',
        ),
    ]
