# Generated by Django 3.2.8 on 2021-11-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_rename_pwd_keys_enc_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='enc_pwd',
            field=models.BinaryField(max_length=255),
        ),
    ]
