# Generated by Django 3.2.8 on 2021-11-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_auto_20211105_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vault',
            name='enc_pwd',
        ),
        migrations.AddField(
            model_name='vault',
            name='pwd',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
